# This is a basic workflow to help you get started with Actions

name: Esther workflow
on:
  workflow_dispatch:
    inputs:
      first:
        description: 'test choice'
        required: false
        type: choice
        options:
          - A
          - B

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo Aaaaaaaa
  B:
    runs-on: ubuntu-latest
    steps:
      - run: echo Bbbb
      - run: exit 1
      - name: catch
        if: ${{ failure() }}
        run: echo bbbcatch
        
  D:
    runs-on: ubuntu-latest
    outputs:
      hello: ${{ steps.world.outputs.world }}
    steps:
      - name: set output
        id: world
        run: echo "::set-output name=world::'world'"
  E:
    needs: D
    runs-on: ubuntu-latest
    steps:
      - run: echo Eeee
      
  F:
    runs-on: ubuntu-latest
    needs: E
    steps:
      - run: echo hello ${{ needs.D.outputs.hello }}
      - run: echo hello ${{ needs.E.outputs.hello }}


