# This is a basic workflow to help you get started with Actions

name: Esther workflow

on:
  workflow_dispatch:
    inputs:
      description: 'test choice'
      required: false
      type: choice
      options:
        - A
        - B

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo Aaaaaaaa
  B:
    runs-on: ubuntu-latest
    steps:
      - run: echo Bbbb
      - run: exit 1
      - name: catch
        if: ${{ failure() }}
        uses: actions/checkout@v2
        
  C:
    runs-on: ubuntu-latest
    if: contains(fromJson('["A", "B"]'), 'B')
    steps:
      - run: echo Ccccc

  D:
    runs-on: ubuntu-latest
    if: github.repository == 'estherkim/good-bot' || github.repository == 'estherkim/bad-bot'
    steps:
      - run: echo Dddddddd
