# This is a basic workflow to help you get started with Actions

name: Esther workflow
on:
  workflow_dispatch:

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$(date +'%Y-%m-%d %H:%M:%S %Z')"
              
  D:
    runs-on: ubuntu-latest
    outputs:
      hello: ${{ steps.day.outputs.day }}
    steps:
      - name: set output
        id: day
        run: |
          DAY=$(date +%d)
          echo "::set-output name=day::$DAY"
  E:
    needs: D
    runs-on: ubuntu-latest
    if: 4 <= needs.d.outputs.hello && needs.d.outputs.hello  <= 5
    steps:
      - run: echo ${{ needs.D.outputs.hello }}
      - name: test
        env:
          data: >-
            {"release": 
            {"name": "${{ needs.D.outputs.hello }}"}, 
            "promotion": 
            {"releaseName": ${{ needs.D.outputs.hello }}, 
            "time": "time", 
            "channel": "nightly"}}
        run: echo ${{ env.data }}   
      - name: test 2
        env:
          time: $(date +'%Y-%m-%d %H:%M:%S %Z')
        run: echo ${{ env.time }}
  
  F:
    runs-on: ubuntu-latest
    needs: [D, E]
    steps:
      - run: echo D hello ${{ needs.D.outputs.hello }}
      - run: echo E hello ${{ needs.E.outputs.hello }}


