# This is a basic workflow to help you get started with Actions

name: Esther workflow

on:
  workflow_dispatch:
    inputs:
      first:
        description: 'test choice'
        required: false
        type: choice
        options:
          - A
          - B

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo Aaaaaaaa
  B:
    runs-on: ubuntu-latest
    steps:
      - run: echo Bbbb
      - run: exit 1
      - name: catch
        if: ${{ failure() }}
        run: echo bbbcatch
        
  C:
    runs-on: ubuntu-latest
    steps:
      - name: POST request
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://api.github.com/repos/estherkim/good-bot/actions/workflows/kim.yml/dispatches'
          data: '{"ref": "main", "inputs": {"letter": ${{ github.event.inputs.first }} }}'
          bearerToken: ${{ secrets.ESDERP_TOKEN }}

  D:
    runs-on: ubuntu-latest
    if: github.repository == 'estherkim/good-bot' || github.repository == 'estherkim/bad-bot'
    steps:
      - run: echo Dddddddd
