
# This is a basic workflow to help you get started with Actions

name: Kim workflow

on:
  pull_request:
    types:
      - closed
    paths:
      - 'configs/versions.json'

  workflow_dispatch:
    inputs:
      a:
        type: string
        required: true
      b:
        type: string
        required: true


jobs:
  A:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.title }}
      - run: echo ${{ github.event.pull_request.body }}
      - run: echo ${{ github.event.pull_request.files }}

  B:
    if: github.event.workflow_dispatch
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.workflow_dispatch.a}} ${{github.event.workflow_dispatch.b}}
