
# This is a basic workflow to help you get started with Actions

name: Kim workflow

on:
  pull_request:
    types:
      - closed
    paths:
      - 'configs/versions.json'

  workflow_dispatch:
    inputs:
      a:
        type: string
      b:
        type: string
      amp-version:
        type: string
      channel:
        type: string


jobs:
  A:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.title }}
      - run: echo ${{ github.event.pull_request.body }}
      - run: echo ${{ github.event.pull_request.files }}

  B:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.inputs.a}} ${{github.event.inputs.b}}
      
      
  C:
    runs-on: ubuntu-latest
    if: github.event.inputs.a == 'run'
    steps:
      - run: echo hello
      
  D:
    needs: [B, C]
    runs-on: ubuntu-latest
    steps:
      - run: echo world
      
  E:
    runs-on: ubuntu-latest
    steps:
    - name: Create event on release calendar
      uses: fjogeleit/http-request-action@v1
      with:
        url: '${{ secrets.CALENDAR_URI }}'
        customHeeaders: '{"Authorization": "Basic ${{ secrets.CALENDAR_TOKEN }}"}'
        data: >
          {
            "release":
            {
              "name": "${{ github.event.inputs.amp-version }}"
            },
            "promotion":
            {
              "releaseName": "${{ github.event.inputs.amp-version }}",
              "time": "$(date +'%Y-%m-%d %H:%M:%S %Z')",
              "channel": "${{ github.event.inputs.channel }}"
            }
          }
      
