name: matrix

on:
  workflow_dispatch:
  
jobs:
  A: 
    runs-on: ubuntu-latest
    outputs:
      fruits: ${{ steps.all.outputs.fruits }}
      veggies: ${{ steps.all.outputs.veggies }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - id: all
        run: |
          ALL=$(npx node ./food-matrix.js)
          VEGGIES="$(echo $ALL | jq '.veggies')"
          FRUITS="$(echo $ALL | jq '.fruits')"
          echo "::set-output name=veggies::{"include":"${VEGGIES}"}"
          echo "::set-output name=fruits::{"include":"${FRUITS}"}"

  E:
    needs: A
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.A.outputs.fruits) }}
    steps:
      - run: echo ${{matrix.color}} ${{ matrix.fruit }}

  F:
    needs: A
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.A.outputs.veggies) }}
    steps:
      - run: echo ${{matrix.color}} ${{ matrix.veggie }}        
