name: matrix

on:
  workflow_dispatch:
  
jobs:
  A: 
    runs-on: ubuntu-latest
    outputs:
      fruits: ${{ steps.fruits.outputs.fruits }}
      veggies: ${{ steps.veggies.outputs.veggies }}
      color-fruits: ${{ steps.color-fruits.outputs.color-fruits }}
      all: ${{ steps.all.outputs.all }}
    steps:
      - id: fruits
        run: |
          FRUITS="['apple', 'plum', 'kiwi']"
          echo "::set-output name=fruits::$FRUITS"
      - id: veggies
        run: |
          VEGGIES="['onion', 'celery', 'carrot']"
          echo "::set-output name=veggies::$VEGGIES"
      - id: color-fruits
        run: |
          COLORFRUITS="[{'color': 'red', 'fruit': 'apple'}, {'color': 'red', 'fruit': 'plum'}]"
          echo "::set-output name=color-fruits::{\"include\":${COLORFRUITS}}"
      - id: all
        run: |
          ALL="{fruits: [{'color': 'red', 'fruit': 'apple'}, {'color': 'red', 'fruit': 'plum'}], veggies: [{'color': 'pink':, 'veggie': 'onion'}, {'color': 'pink':, 'veggie': 'tree'}]}"
          echo "::set-output name=all::{\"include\":$ALL}"        

#   B:
#     needs: A
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: ${{ fromJson(needs.A.outputs.fruits) }}
#     steps:
#       - run: echo ${{ matrix.fruit }}
      
#   C:
#     needs: A
#     runs-on: ubunut-latest
#     strategy:
#       matrix:
#         veggie: ${{ fromJson(needs.A.outputs.veggies) }}
#     steps:
#       - run: echo ${{ matrix.veggie }}

#   D:
#     needs: A
#     runs-on: ubuntu-latest
#     strategy:
#       matrix: ${{ fromJson(needs.A.outputs.color-fruits) }}
#     steps:
#       - run: echo ${{matrix.color}} ${{ matrix.fruit }}

  E:
    needs: A
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.A.outputs.all.fruits) }}
    steps:
      - run: echo ${{matrix.color}} ${{ matrix.fruit }}

  F:
    needs: A
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.A.outputs.all.veggies) }}
    steps:
      - run: echo ${{matrix.color}} ${{ matrix.veggie }}        
