name: matrix

on:
  workflow_dispatch:
  
jobs:
  A: 
    runs-on: ubuntu-latest
    outputs:
      fruits: ${{ steps.fruits.outputs.fruits }}
      veggies: ${{ steps.veggies.outputs.veggies }}
    steps:
      - id: fruits
        run: |
          FRUITS="['apple', 'plum', 'kiwi']"
          echo "::set-output name=fruits::$FRUITS"
      - id: veggies
        run: |
          VEGGIES="['onion', 'celery', 'carrot']"
          echo "::set-output name=veggies::$VEGGIES"
          

  B:
    needs: A
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: ${{ fromJson(needs.A.outputs.fruits) }}
    steps:
      - run: echo ${{ matrix.fruit }}
      
  C:
    needs: A
    runs-on: ubunut-latest
    strategy:
      matrix:
        veggie: ${{ fromJson(needs.A.outputs.veggies) }}
    steps:
      - run: echo ${{ matrix.veggie }}
        
