# This is a basic workflow to help you get started with Actions

name: On Merge

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      first:
        type: string
      second:
        type: string
  
  pull_request:
    types:
      - closed

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$(${{ github.event.inputs.first }} +'%Y-%m-%d %H:%M:%S %Z')"
      - run: |
          echo "${{ github.event.pull_request.title }}"
          echo "${{ github.event.pull_request.body }}" 
          echo "${{ github.event.pull_request.number }}"

