# This is a basic workflow to help you get started with Actions

name: On Merge

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      job:
        type: string
        required: true
  
  pull_request:
    types:
      - closed

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.pull_request.title }}"
          echo "${{ github.event.pull_request.body }}" 
          echo "${{ github.event.pull_request.number }}"

