name: patch

on:
  workflow_dispatch:
    inputs:
      build-number:
        description: format build to cherry-pick, in the form of YYMMDD.N
        required: true
        type: string
      shas:
        description: commit sha(s) from `main` to cherry-pick with (i.e. abcdef1 abcdef2)
        required: true
        type: string

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Increment patch by one
        id: get-cp-build-number
        run: |
          # get build number to be cherry-picked
          BUILD_NUMBER=${{ github.event.inputs.build-number }}
          # increment the patch number by one
          PATCH_NUMBER="${BUILD_NUMBER#*.}" # get the `N` of `YYMMDD.N`
          echo "New patch number will be $((++PATCH_NUMBER))"
          # generate the cherry-pick build number
          VERSION_NUMBER="${BUILD_NUMBER%.*}" # get the `YYMMDD` of `YYMMDD.N`
          CP_BUILD_NUMBER="${VERSION_NUMBER}.${PATCH_NUMBER}"
          echo "cp-build-number=${CP_BUILD_NUMBER}" >> $GITHUB_OUTPUT
      - name: Set git config
        run: |
          NAME=$(git --no-pager log --format=format:'%an' -n 1)
          EMAIL="$(git --no-pager log --format=format:'%ae' -n 1)"
          git config --global user.name $NAME
          git config --global user.email $EMAIL
      - name: Cherry-pick ${{ github.event.inputs.build-number }} with ${{ github.event.inputs.shas }}
        run: |
          git checkout -b ${{ steps.get-cp-build-number.outputs.cp-build-number }} origin/${{ github.event.inputs.build-number }}
          git cherry-pick -x ${{ github.event.inputs.shas }}
          git push --set-upstream origin ${{ steps.get-cp-build-number.outputs.cp-build-number }}
