name: Publish NPM Packages
on:
  workflow_dispatch:
    inputs:
      ampversion:
        description: "AMP version"
        required: true
      tag:
        description: "NPM package tag"
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension: ["amp-esther", "amp-luna"]
    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.events.inputs.ampversion }} OK THIS WORKs
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
      - name: Build package
        run: |
          npm install
          node ${{ github.workspace }}/build-system/publish-npm/build-npm-binaries.js ${{ matrix.extension }}
          node ${{ github.workspace }}/build-system/publish-npm/write-package-json.js ${{ matrix.extension }} ${{ github.event.inputs.ampversion }}
      - name: Publish v1
        run: |
          cd ${{ github.workspace }}/extensions/${{ matrix.extension }}/1.0 
          npm install
          cat /home/runner/work/_temp/.npmrc
          npm whoami
          npm publish --access public --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish v2 if exists
        run: |
          if $(test -d ${{ github.workspace }}/extensions/${{ matrix.extension }}/2.0); then            
            npm publish ${{ github.workspace }}/extensions/${{ matrix.extension }}/2.0 --access public --tag ${{ github.event.inputs.tag }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
