name: publish npm packages
on:
  workflow_dispatch:
    inputs:
      ampversion:
        description: "AMP version"
        required: true
      tag:
        description: "NPM package tag (latest | nightly)"
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      extensions: ${{ steps.get-extensions.outputs.extensions }}
    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.events.inputs.ampversion }} OK THIS WORKs
      - name: Get extensions to publish
        id: get-extensions
        run: |
          EXTENSIONS=$(node ./build-system/publish-npm/get-extensions.js)          
          echo "::set-output name=extensions::{\"include\":${EXTENSIONS}}"
  publish:
    environment: NPM_TOKEN
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.extensions) }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.events.inputs.ampversion }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      # - name: Build package
      #   run: |
      #     npm install
      #     node ./build-system/publish-npm/build-npm-binaries.js ${{ matrix.extension }}
      #     node ${{ github.workspace }}/build-system/publish-npm/write-package-json.js ${{ matrix.extension }} ${{ github.event.inputs.ampversion }} ${{ github.event.inputs.tag }}
      - name: Publish or upgrade v1
        run: |
          if $(${{ github.event.inputs.tag }} == 'latest'); then
            NPM_PACKAGE=$(jq -r .name ./extensions/${{ matrix.extension }}/1.0/package.json)
            NPM_VERSION=$(jq -r .version ./extensions/${{ matrix.extension }}/1.0/package.json)
            npm dist-tag add ${{  NPM_PACKAGE  }}@${{ NPM_VERSION }} latest
          else
            npm publish ./extensions/${{ matrix.extension }}/1.0 --access public --tag ${{ github.event.inputs.tag }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Publish v2 if exists
      #   run: |
      #     if $(test -d ${{ github.workspace }}/extensions/${{ matrix.extension }}/2.0); then
      #       npm publish ${{ github.workspace }}/extensions/${{ matrix.extension }}/2.0 --access public --tag ${{ github.event.inputs.tag }}
      #     fi
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
