name: Require QA Approval

on:
  pull_request_review:
    types: [submitted]
  
jobs:
  is-approved-by-qa:
    if: "!startsWith(github.pull_request.head.ref, 'test-job-1') && !startsWith(github.pull_request.head.ref, 'test-job-2')"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.head.ref }}
          echo "This PR does not require approval from QA"
