name: QA Check

on:
  pull_request:
    paths:
      - 'configs/versions.json'

jobs:
  require-qa:
    if: startsWith(github.head_ref, 'test-promote-1') || startsWith(github.head_ref, 'test-promote-2')
    runs-on: ubuntu-latest
    steps:
      - run: echo Aaaaa
