name: QA Check

on:
  pull_request:
    paths:
      - 'configs/versions.json'

jobs:
  require-qa:
    if: startsWith(env.GITHUB_HEAD_REF, 'test-promote-1') || startsWith(env.GITHUB_HEAD_REF, 'test-promote-2')
    runs-on: ubuntu-latest
    steps:
      - run: echo Aaaaa
