name: Require QA Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  is-approved:
    if: startsWith(github.event.pull_request.head.ref, 'test-promote-1') || startsWith(github.event.pull_request.head.ref, 'test-promote-2')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if not approved
        if: ${{ github.event.review.state != 'approved' }} 
        run: |
          echo "Stable and Beta 1% promotions require QA approval"
          exit 1
      - name: Check approver team membership
        id: checkUserMember
        uses: tspascoal/get-user-teams-membership@v1
        with:
          username: ${{ github.event.review.user.login }}
          organization: 'ampproject'
          team: 'amp-qa'
          GITHUB_TOKEN: ${{ secrets.READ_ORG }}
      - name: debug
        run: echo ${{ steps.checkUserMember.outputs.isTeamMember }}
      - name: Fail if approver is not QA
        if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
        run: |
          echo "${{ github.event.review.user.login }} is not a member of @ampproject/amp-qa"
          exit 1
